### PR TITLE
Replace usage of obsolete `VFile#warn` to new `VFile#message`

### LINKED ISSUE #7: `file.warn` is `undefined`
https://github.com/RichardLitt/remark-lint-appropriate-heading/blob/3259a6e7191f7115f0fa0f1e82aa7f866461b354/lib/appropriate-heading.js#L56

Seems dependencies of `standard-readme` and `standard-readme-cli` got obsolete and API has changed. There's now a `file.fail`but not sure if it has the same purposse.

```json
  "dependencies": {
    "remark": "^11.0.2",
    "standard-readme-preset": "^1.0.4",
    "to-vfile": "^6.0.0"
  },
```

### PR DESCRIPTION
**Pull request by piranna**
Fix #7

### CODE REVIEW

**Comment by piranna** [comment]
I tried to update the other dependencies besides `vfile`, but tests are failling with them. Not sure if we should update and fix them too, or if it's not needed...

**Comment by RichardLitt** [comment]
Thank you, @piranna!

**Comment by piranna** [comment]
Welcome :-) Is this published to npm?

**Comment by RichardLitt** [comment]
Yep!

**Comment by piranna** [comment]
Great! :-D

**Pull request merged**
